//! Route definitions: the unit the routing macros produce.

use crate::operation::OperationContext;
use crate::request::Request;
use crate::response::Response;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

/// A boxed, `Send` future — the currency of the dynamic parts of the crate.
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// An erased request handler.
pub type HandlerFn = Arc<dyn Fn(Request) -> BoxFuture<'static, Response> + Send + Sync>;

/// One method on one path, plus the code that documents it.
#[derive(Clone)]
pub struct RouteDef {
    /// Uppercase HTTP method.
    pub method: &'static str,
    /// The route template, with `{name}` and `{*rest}` placeholders.
    pub path: &'static str,
    /// The handler, already erased.
    pub handler: HandlerFn,
    /// Fills in the OpenAPI operation. Generated by the routing macros from
    /// the handler signature.
    pub describe: fn(&mut OperationContext<'_>),
}

impl RouteDef {
    /// Builds a route from a closure, for handlers written without the
    /// attribute macros. The operation is left undocumented beyond its path
    /// and method — reach for `#[get]`/`#[post]` to get the document for free.
    pub fn raw<F, Fut>(method: &'static str, path: &'static str, handler: F) -> Self
    where
        F: Fn(Request) -> Fut + Send + Sync + 'static,
        Fut: Future<Output = Response> + Send + 'static,
    {
        RouteDef {
            method,
            path,
            handler: Arc::new(move |req| Box::pin(handler(req))),
            describe: |_| {},
        }
    }

    /// Replaces the describe hook, e.g. to document a raw route by hand.
    pub fn described(mut self, describe: fn(&mut OperationContext<'_>)) -> Self {
        self.describe = describe;
        self
    }
}

impl std::fmt::Debug for RouteDef {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RouteDef")
            .field("method", &self.method)
            .field("path", &self.path)
            .finish_non_exhaustive()
    }
}

/// Anything that can be mounted on a [`crate::Router`].
///
/// The routing macros generate a hidden unit struct implementing this, which
/// is why `routes![create_user]` works while `create_user` stays a normal
/// callable function.
pub trait IntoRoute {
    fn into_route(self) -> RouteDef;
}

impl IntoRoute for RouteDef {
    fn into_route(self) -> RouteDef {
        self
    }
}

/// The suffix appended to a handler's name to reach its generated route type.
///
/// `routes!` uses this to turn `create_user` into `create_user__route`, which
/// is how the handler keeps its own name and stays directly callable in tests.
pub const ROUTE_SUFFIX: &str = "__route";
